# Generated by Django 3.2 on 2024-02-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsubtraction',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_purchases', to='vendors.phonenumber'),
        ),
        migrations.AddField(
            model_name='creditsubtraction',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtractions', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='creditaddition',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='vendors.vendor'),
        ),
    ]
